global:
  algoliaApiKeyName: "firestore-algolia-search-extension-write-api-key"
  forceDataSync: "no" # defaults to 'no'
  location: "us-west2" # defaults to 'us-west2'
  environments:
    lester:
      namespace: dev
      prefix: swarm-work
      algoliaIndexes:
        - profiles
        - projects
    aaron:
      namespace: dev
      prefix: swarm-work
      algoliaIndexes:
        - swarms
        - skills

algoliaIndexes: []

algoliaApiKeys:
  - name: skills
    acls: ["search"]
    indexes: ["profiles"]
    description: "API key for profiles"
  - name: swarms
    acls: []
