kind: Environment
name:
  type: string
  required: true
spec:
  type: object
  required: true
  object:
    environment:
      type: object
      required: false
      autoCreate: true
      object:
        updateExtensions:
          type: boolean
          required: false
          autoCreate: true
          default: true
        updateCollections:
          type: boolean
          required: false
          autoCreate: true
          default: false
    gcp:
      type: object
      required: false
      autoCreate: false
      object:
        project:
          type: string
          required: true
        region:
          type: string
          required: false
          autoCreate: true
          default: us-west2
        forceDataSync:
          type: boolean
          required: false
          autoCreate: true
          default: false
    pulumi:
      type: object
      required: false
      autoCreate: false
      object:
        namespace:
          type: string
          required: false
          autoCreate: true
          default: ""
        prefix:
          type: string
          required: false
          autoCreate: true
          default: ""
        stack:
          type: string
          required: true
    algolia:
      type: object
      required: false
      autoCreate: false
      object:
        apiKeyName:
          type: string
          required: false
          autoCreate: true
          default: ""
        appId:
          type: string
          required: false
          autoCreate: true
          default: ""
